[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Redirect rules
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Force refresh for debugging
[[redirects]]
  from = "/refresh"
  to = "/index.html?refresh=true"
  status = 302
